# 调用

当在代码中调用`Celery`方法时，作为 `Producer` 选择将会自动连接`broker`,进行任务注册添加，然后放到`broker`中，供`worker`主动连接`broker`，然后获取任务执行

1. 可以使用 `delay()` 方法进行调用：

   `>>> add.delay(2, 2)`

2. `delay()` 实际上为 `apply_async()` 的快捷使用：

   `>>> add.apply_async((2, 2))`

3. `apply_async()` 可以指定调用时执行的参数，例如运行的时间，使用的任务队列等：

   `>>> add.apply_async((2, 2), queue='lopri', countdown=10)`

上面的实例中，任务被下发到 `lopri` 队列中，任务下发之后会在最早 10 秒内执行。 直接调用任务函数进行执行任务，不会发送任何任务消息：

`>>> add(2, 2)`
`4`

`delay()` `apply_async()` 以及 `apply(__call__)` 为 Celery 调用的 API，也可以用于签名。

> 调用任务：`Calling Tasks` 章节中详细的描述了 `Calling API` 使用。

---

1. 每一个任务被调用时会赋值一个的任务 ID（UUIID）。

2. `delay()` 和 `apply_async()` 方法会返回一个 `AsyncResult` 实例，可以用于进行跟踪任务状况。如果进行跟踪任务状态，需要设置一个结果后端，以便于存储。

3. 默认情况下禁用结果，因为没有一个适合所有应用程序的结果后端，对于大量的任务来说，保存返回内容不是非常有用的，所以该默认值是一个比较合理的。

4. 另外，结果后端不是用于监控任务以及职程（`Worker`），`Celery` 有专用的事物消息来进行监控（详情请参阅：监控和管理手册：`Monitoring and Management Guide`）。

- 如果配置了结果后端，可以获取任务的返回值：

  ```py
  >>> res = add.delay(2, 2)
  >>> res.get(timeout=1)
  4
  ```

- 也可以通过 id 属性进行获取任务的 ID：

  ```py
  >>> res.id
  d6b3aea2-fb9b-4ebc-8da4-848818db9114
  ```

- 如果任务执行引发异常，可以进行检查异常以及溯源，默认情况下 result.get() 会抛出异常：

  ```py
  >>> res = add.delay(2)
  >>> res.get(timeout=1)

  Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/devel/celery/celery/result.py", line 113, in get
      interval=interval)
  File "/opt/devel/celery/celery/backends/rpc.py", line 138, in wait_for
      raise meta['result']
  TypeError: add() takes exactly 2 arguments (1 given)
  ```

- 如果不希望 Celery 抛出异常，可以通过设置 propagate 来进行禁用：

  ```py
  >>> res.get(propagate=False)
  TypeError('add() takes exactly 2 arguments (1 given)',)
  ```

- 在这种情况下，他可以返回引发错误的实例，需要检查任务是否执行成功还是失败，可以通过在结果实例中使用对应的方法：

  ```py
  >>> res.failed()
  True

  >>> res.successful()
  False
  ```

- 如何知道任务是否执行失败？可以通过查看任务的 state 进行查看：

  ```py
  >>> res.state
  'FAILURE'
  ```

> 一个任务只能有当前只能有一个状态，但他的执行过程可以为多个状态，一个典型的阶段是：

`PENDING -> STARTED -> SUCCESS`

> 启动状态是一种比较特殊的状态，仅在 `task_track_started` 启用设置或 `@task(track_started=True)` 的情况下才会进行记录。

挂起状态实际上不是记录状态，而是未知任务 ID 的默认状态，可以从此实例中看到：

    ```py
    >>> from proj.celery import app

    >>> res = app.AsyncResult('this-id-does-not-exist')
    >>> res.state
    'PENDING'
    ```

- 重试任务比较复杂，为了证明，一个任务会重试两次，任务的阶段为：

`PENDING -> STARTED -> RETRY -> STARTED -> RETRY -> STARTED -> SUCCESS`

更多任务状态信息可以查阅用户指南中的任务：`Tasks` 章节的 `State` 部分内容。
更多调用任务信息可以参阅调用任务：[Calling Tasks](https://www.celerycn.io/yong-hu-zhi-nan/tiao-yong-ren-wu-calling-tasks)。
